#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 21 15:50:49 2019

@author: laura

This program takes the CSV files generated by linkage_csv.py and loads them into the 
corresponding tables M04, M06 or M052
"""

# import statements
import cgi, cgitb
cgitb.enable()
import sys, os
import codecs
import cx_Oracle
sys.stdout = codecs.getwriter("utf-8")(sys.stdout.detach())
# Authentication information
user = 'sys'
pw = 'oracle'
server = 'orc1'

# Establish connection to Oracle database
dsn_tns = cx_Oracle.makedsn('Host Name', 'Port Number', service_name='Service Name')
conn = cx_Oracle.connect(user=r'User Name', password='Personal Password', dsn=dsn_tns)

# set up the cursor
try:
	c = conn.cursor()
except:
	print("Unable to connect to the database")
	return

# create the query (as a string)
try:
	query = "sqlldr "+user+"/"+pw+"@"+server+" control=loader.ctl"
	# run the query
	c.execute(query)
except:
	print("There was an error opening SQL Loader")
	return
"""
Integrate with linkage_csv and load new csv's into the database as they are created
"""
query = '''
			load data infile '''+new_data'''
 			append into table ''' machine.upper()'''
 			fields terminated by "," skip 1
		'''
c.execute(query)
# close the connection
conn.close()